### ISSUE TITLE
SqrtmassA in the code

### ISSUE THREAD

**Issue by sean-xr** [flrneha/ElasticBasisForSpectralMatching#1]
Dear Author,

Thanks for the well-organized code and well explained paper. However, I had one confusion in your code. In Solver.py, when we're computing the functional map from point correspondence, the code uses 'square root of diagonal mass matrix A' , the code is as follows:
C = np.linalg.pinv(self.sqrtmassA.dot(self.basisA[:, :k])).dot(
                self.sqrtmassA.dot(P.T.dot(self.basisB[:, :k])))
While in the paper, this process is formulated as:
![20751702160504_ pic](https://github.com/flrneha/ElasticBasisForSpectralMatching/assets/91930856/0e887d5c-a76c-4013-a28d-4628abe45415)

I would like to ask why are we using the squared root of diagonal mass matrix here, rather than the mass matrix computed from igl?

Thanks for the answer.

**Comment by flrneha** [comment]
Dear @sean-xr ,
the two ways of computation are equivalent.
The euclidean pseudoinverse of $\sqrt{M}\Phi_{k}$ is given by  $(\Phi_{k}^T \sqrt{M}^T \sqrt{M} \Phi_k)^{-1} \Phi_k^{T} \sqrt{M}^T = M_k^{-1} \Phi_k^{T} \sqrt{M}^T $. 
Hence, `np.linalg.pinv(self.sqrtmassA.dot(self.basisA[:, :k])).dot(self.sqrtmassA) `is the same as (3). 
This way of implementing the pseudo inverse turned out to be a bit more efficient than naively implementing the formula (3). Probably, because np.linalg.pinv uses an efficient routine by computing the SVD.
The mass matrix from igl is a lumped mass matrix which is diagonal, so self.massA.diagonal() allows to treat the matrix as a diagonal matrix and is again just used for efficiency.

I hope this answers your question, otherwise feel free to reach out again.
